
package Telas;

import Dao_controller.criar_candidatura;
import Modelo.Candidatov2;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author iader
 */
public class Tela_de_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Tela_de_cadastro
     */
    public Tela_de_cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        candidato_cpf = new javax.swing.JTextField();
        candidato_nome = new javax.swing.JTextField();
        candidato_nascimento = new javax.swing.JTextField();
        candidato_telefone = new javax.swing.JTextField();
        candidato_email = new javax.swing.JTextField();
        candidato_senha = new javax.swing.JPasswordField();
        inscricao_send = new javax.swing.JButton();
        titulo_pag = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(710, 520));

        jLabel1.setText("Cpf:");

        jLabel2.setText("nome completo:");

        jLabel3.setText("data de nascimento:");

        jLabel4.setText("telefone:");

        jLabel5.setText("email:");

        jLabel6.setText("senha:");

        candidato_cpf.setText("Somente numeros");
        candidato_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato_cpfActionPerformed(evt);
            }
        });

        candidato_nascimento.setText("formato ano-mes-dia (ex:1994-01-22)");

        candidato_telefone.setText("Somente numeros (ex: 84999012534)");

        candidato_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                candidato_emailActionPerformed(evt);
            }
        });

        inscricao_send.setText("Realizar inscrição");
        inscricao_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscricao_sendActionPerformed(evt);
            }
        });

        titulo_pag.setText("Insira os dados do candidato nos campos abaixo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(candidato_telefone)
                        .addComponent(candidato_senha)
                        .addComponent(candidato_nome)
                        .addComponent(candidato_cpf)
                        .addComponent(candidato_email)
                        .addComponent(candidato_nascimento))
                    .addComponent(inscricao_send)
                    .addComponent(titulo_pag)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo_pag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidato_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(candidato_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidato_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidato_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidato_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(candidato_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inscricao_send)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void candidato_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidato_cpfActionPerformed

    private void candidato_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_candidato_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_candidato_emailActionPerformed

    private void inscricao_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscricao_sendActionPerformed
    Candidatov2 candidato = new Candidatov2();
    candidato.setCpf(candidato_cpf.getText());
    candidato.setNome_sobrenome(candidato_nome.getText());
    candidato.setData_nascimento(candidato_nascimento.getText());
    candidato.setTelefone(candidato_telefone.getText());
    candidato.setEmail(candidato_email.getText());
    candidato.setSenha(candidato_senha.getText());

    if((candidato_cpf.getText().isEmpty() || (candidato_nome.getText().isEmpty())
            || (candidato_nascimento.getText().isEmpty()) ||
            (candidato_telefone.getText().isEmpty()) || (candidato_email.getText().isEmpty())
            || candidato_senha.getText().isEmpty())){
            JOptionPane.showMessageDialog(null, "todos os campos "
                    + "devem ser preenchidos!");
        }
        else{
            criar_candidatura inscricao = new criar_candidatura();
            inscricao.criar(candidato);
            JOptionPane.showMessageDialog(null, "Inscrição de "
                    + candidato_nome.getText() +
                    " realizada com sucesso");
             this.dispose(); 
        }
    
    }

// Método para converter String em Date
private Date parseDate(String dateString) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd");
    try {
        return dateFormat.parse(dateString);
    } catch (ParseException e) {
        e.printStackTrace();
    }
    return null;
    }//GEN-LAST:event_inscricao_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_de_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField candidato_cpf;
    private javax.swing.JTextField candidato_email;
    private javax.swing.JTextField candidato_nascimento;
    private javax.swing.JTextField candidato_nome;
    private javax.swing.JPasswordField candidato_senha;
    private javax.swing.JTextField candidato_telefone;
    private javax.swing.JButton inscricao_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel titulo_pag;
    // End of variables declaration//GEN-END:variables
}
